[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a_\0\0\x4\x37\0\0\0\0\0\0\0\0\0\0\a_\0\0\x4\x37\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\a_\0\0\x4\x37)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\a`\0\0\x4\x38\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
app=true
donation_message=true
show_msg=false
show_name=true
show_photo=false
show_sound=false
sound=false
theme_tray=symbolic_dark

[onboarding]
completed=true
initial_setup_completed=true
last_environment=local
version=2

[performance]
auto_gpu_workaround=true
cache_size_max=0
cache_type=DiskHttpCache
disable_accessibility=false
disable_gpu=false
disable_gpu_vsync=false
force_gbm=false
in_process_gpu=false
js_memory_limit_index=0
js_memory_limit_mb=0
js_predictable_gc_schedule=false
persistent_cookies=true
process_per_site=true
single_process=false
software_rendering=false
software_video_decoding=false

[permissions]
auto_grant\camera=false
auto_grant\camera_microphone=false
auto_grant\microphone=false
auto_grant\screen_contents=false
auto_grant\screen_contents_audio=false

[system]
DontUseNativeDialog=true
background_message=false
confirm_on_close=false
donation_message=false
download_path=/home/eren/Downloads
folderDownloads=false
hide_bar_users=true
interface_language=system
keep_background=true
menubar=false
notificationCounter=false
quit_in_close=false
scale=100
sidebar=false
spellCheckLanguage=en_GB
spellCheckLanguages=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\n\0\0\0\n\0\x65\0n\0_\0G\0\x42)
spellCheckProvisionedLocale=en_GB
spellCheckers=false
start_background=true
start_system=false
theme=auto
tray_icon=true
tray_theme=default
wayland=true

[web]
background_throttling=true
ctrl_arrow_visual_navigation_fix=true
disable_animations=false
disable_pinch=false
scroll_animator=false

[website]
open_page=false
