[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x3\xef\0\0\0\x1\0\0\0\x19\0\0\a~\0\0\x4\b\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x3\xef)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\a\x80\0\0\x3\xf0\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
app=true
show_msg=false
show_name=true
show_photo=false
show_sound=false
theme_tray=symbolic_dark

[performance]
cache_size_max=100
in_process_gpu=false

[system]
DontUseNativeDialog=false
background_message=false
donation_message=false
download_path=/home/eren/Downloads
folderDownloads=false
hide_bar_users=true
keep_background=true
menubar=false
notificationCounter=true
scale=100
sidebar=false
spellCheckers=false
start_background=true
start_system=true
theme=dark
tray_theme=default
wayland=true

[web]
scroll_animator=false

[website]
open_page=false
